/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.Campaña;
import aivon.entidades.Producto;
import aivon.entidades.Revendedor;
import aivon.modelos.CampañaData;
import aivon.modelos.Conexion;
import aivon.modelos.ProductoData;
import aivon.modelos.RevendedorData;
import static java.lang.ProcessBuilder.Redirect.to;
import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
    
/**
 *
 * @author Genaro
 */
public class CampañaActualizar extends javax.swing.JInternalFrame {
    private Conexion conexion;
    private CampañaData cd;
    private RevendedorData rd;
    private Campaña campaña;
    
    
    private DefaultTableModel modelo;
    /**
     * Creates new form ProductoActualizar
     */
    public CampañaActualizar() {
        initComponents();
        try {
            conexion = new Conexion();
            cd = new CampañaData(conexion);
            rd = new RevendedorData(conexion);
            modelo = new DefaultTableModel();
            armaCabeceraTabla();
            cargaCampañas();
            deshabilitarCampos();
        } catch (Exception e) {
        }
    }

    private void armaCabeceraTabla() {
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("Fecha de Inicio");
        columnas.add("Fecha de Fin");
        columnas.add("Monto Minimo");
        columnas.add("Monto Maximo");
        columnas.add("Activo");
        
        columnas.forEach((it) -> {
            modelo.addColumn(it);
        });
        jt_campañas.setModel(modelo);
    }
    
    private void borraFilasTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void cargaCampañas() {
        this.borraFilasTabla();

        List<Campaña> lista = cd.buscarCampañas();
        lista.forEach((p) -> {
            if (p.isActiva()) {
                modelo.addRow(new Object[]{p.getId_campaña(), p.getNombre(), p.getFecha_inicio(), p.getFecha_fin(), p.getMonto_min(), p.getMonto_max(), "Sí"});
            } else {
                modelo.addRow(new Object[]{p.getId_campaña(), p.getNombre(), p.getFecha_inicio(), p.getFecha_fin(), p.getMonto_min(), p.getMonto_max(), "No"});
            }
            
        });

    }
    
    private void deshabilitarCampos() {
        jtf_nombre.setEnabled(false);
        jtf_montoMinimo.setEnabled(false);
        jtf_montoMaximo.setEnabled(false);
        jrb_activo_si.setSelected(false);
        jrb_activo_no.setSelected(false);
        jrb_activo_si.setEnabled(false);
        jrb_activo_no.setEnabled(false);
        jb_cargar.setEnabled(false);
        jb_limpiar.setEnabled(false);
        //jb_baja.setEnabled(false);
    }
    
    private void habilitarCampos() {
        jtf_nombre.setEnabled(true);
        jtf_montoMinimo.setEnabled(true);
        jtf_montoMaximo.setEnabled(true);
        jrb_activo_si.setSelected(true);
        jrb_activo_no.setSelected(true);
        jrb_activo_si.setEnabled(true);
        jrb_activo_no.setEnabled(true);
        jb_cargar.setEnabled(true);
        jb_limpiar.setEnabled(true);
        //jb_baja.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_jrb_activo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_campañas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jb_modificar_campaña_sel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jL_montoMinimo = new javax.swing.JLabel();
        jl_montoMaximo = new javax.swing.JLabel();
        jtf_montoMinimo = new javax.swing.JTextField();
        jtf_montoMaximo = new javax.swing.JTextField();
        jb_limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jb_cargar = new javax.swing.JButton();
        jrb_activo_si = new javax.swing.JRadioButton();
        jbt_salir = new javax.swing.JButton();
        jrb_activo_no = new javax.swing.JRadioButton();
        jl_activo = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser_inicio = new com.toedter.calendar.JDateChooser();
        jl_fin = new javax.swing.JLabel();
        jDateChooser_fin = new com.toedter.calendar.JDateChooser();

        jt_campañas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_campañas);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jb_modificar_campaña_sel.setText("MODIFICAR CAMPAÑA SELECCIONADA");
        jb_modificar_campaña_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificar_campaña_selActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA INICIO");

        jL_montoMinimo.setText("MONTO MINIMO");

        jl_montoMaximo.setText("MONTO MAXIMO");

        jtf_montoMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_montoMinimoKeyTyped(evt);
            }
        });

        jtf_montoMaximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_montoMaximoKeyTyped(evt);
            }
        });

        jb_limpiar.setText("LIMPIAR");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE");

        jb_cargar.setText("CARGAR");
        jb_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cargarActionPerformed(evt);
            }
        });

        bg_jrb_activo.add(jrb_activo_si);
        jrb_activo_si.setText("SÍ");
        jrb_activo_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_activo_siActionPerformed(evt);
            }
        });

        jbt_salir.setText("SALIR");
        jbt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salirActionPerformed(evt);
            }
        });

        bg_jrb_activo.add(jrb_activo_no);
        jrb_activo_no.setText("NO");

        jl_activo.setText("ACTIVO");

        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ACTUALIZACIÓN DE CAMPAÑAS");

        jl_fin.setText("FECHA FIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jl_activo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                                .addComponent(jrb_activo_si)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jrb_activo_no))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jL_montoMinimo)
                                                    .addComponent(jl_montoMaximo))
                                                .addGap(73, 73, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtf_montoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtf_montoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jb_limpiar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jb_cargar)))
                                        .addComponent(jbt_salir))
                                    .addComponent(jb_modificar_campaña_sel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jl_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_nombre)
                                    .addComponent(jDateChooser_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_modificar_campaña_sel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_fin)
                            .addComponent(jDateChooser_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_montoMinimo)
                            .addComponent(jtf_montoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_montoMaximo)
                            .addComponent(jtf_montoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_activo)
                            .addComponent(jrb_activo_si)
                            .addComponent(jrb_activo_no))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_limpiar)
                            .addComponent(jb_cargar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_salir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_montoMinimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_montoMinimoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')|| (caracter > '9')) && (caracter != '\b') &&(caracter != '.')) {
            evt.consume();
        }
        if(!(jtf_montoMinimo.getText().length()<7)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_montoMinimoKeyTyped

    private void jtf_montoMaximoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_montoMaximoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')|| (caracter > '9')) && (caracter != '\b') &&(caracter != '.')) {
            evt.consume();
        }
        if(!(jtf_montoMaximo.getText().length()<7)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_montoMaximoKeyTyped

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cargarActionPerformed
        // TODO add your handling code here:
        if (jtf_nombre.getText().length() > 4) {
            campaña.setNombre(jtf_nombre.getText());
            try {
                double monto_min = Double.parseDouble(jtf_montoMinimo.getText());
                if (monto_min > 0) {
                    campaña.setMonto_min(monto_min);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un monto minimo válido");
                jtf_montoMinimo.setText("");
                jtf_montoMinimo.requestFocus();
            }
            try {
                double monto_max = Double.parseDouble(jtf_montoMaximo.getText());
                if (monto_max > campaña.getMonto_min()) {
                    campaña.setMonto_max(monto_max);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un monto maximo mayor que el monto minimo");
                jtf_montoMaximo.setText("");
                jtf_montoMaximo.requestFocus();
            }
            LocalDate fecha;
            fecha = LocalDateTime.ofInstant(jDateChooser_inicio.getDate().toInstant(), ZoneId.systemDefault()).toLocalDate();
            if (jDateChooser_inicio.getDate() != null) {
                campaña.setFecha_inicio(fecha);
                if (jrb_activo_si.isSelected()) {
                    campaña.setActiva(true);
                    cd.desactivarCampañas();
                    cd.modificarCampaña(campaña); 
                    this.cargaCampañas();
                    limpiar();
                } else if (jrb_activo_no.isSelected()) {
                    campaña.setActiva(false);
                    cd.modificarCampaña(campaña); 
                    this.cargaCampañas();
                    limpiar();

                } else {
                    JOptionPane.showMessageDialog(this, "La fecha elegida es nula");
                    jDateChooser_inicio.requestFocus();
                }

            }
        }


        
    }//GEN-LAST:event_jb_cargarActionPerformed

    private void jbt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbt_salirActionPerformed

    private void jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyTyped
        // TODO add your handling code here:
        if(!(jtf_nombre.getText().length()<30)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_nombreKeyTyped

    private void jb_modificar_campaña_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificar_campaña_selActionPerformed
        // BOTON MODIFICAR CAMPAÑA SELECCIONADO
        int fila_sel = jt_campañas.getSelectedRow();
        
        if(fila_sel != -1){
        try{
        int id_campaña = Integer.parseInt(jt_campañas.getValueAt(fila_sel, 0).toString());
        campaña = cd.buscarCampaña(id_campaña);
         }catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Fallo al traer id entero");
         }
        
        System.out.println("El estado activo de la campaña es "+campaña.isActiva());
        this.habilitarCampos();
        jtf_nombre.setText(campaña.getNombre());
        jtf_montoMinimo.setText(String.valueOf(campaña.getMonto_min()));
        jtf_montoMaximo.setText(String.valueOf(campaña.getMonto_max()));
        jDateChooser_inicio.setDate(Date.valueOf(campaña.getFecha_inicio()));
        jDateChooser_fin.setDate(Date.valueOf(campaña.getFecha_fin()));
                
        if (campaña.isActiva()) {
            jrb_activo_no.setSelected(false);
            jrb_activo_si.setSelected(true);
            
        } else {
            jrb_activo_si.setSelected(false);
            jrb_activo_no.setSelected(true);
        
         }
        actualizarNiveles();
        }JOptionPane.showMessageDialog(this, "Debe seleccionar una campaña");
        System.out.println("Debe selecconar una campaña");
        
    }//GEN-LAST:event_jb_modificar_campaña_selActionPerformed
       
    private void actualizarNiveles(){
       List<Revendedor> lista = rd.buscarRevendedores();
       lista.forEach((revendedor) -> {
           
           rd.calcularNivelRevendedor(revendedor);
        });
       
   }
    
    private void jrb_activo_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_activo_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_activo_siActionPerformed
    private void limpiar() {
        jtf_nombre.setText("");

        jtf_montoMinimo.setText("");
        jtf_montoMaximo.setText("");
        jrb_activo_si.setSelected(false);
        jrb_activo_no.setSelected(false);
        jDateChooser_inicio.setDate(null);
        jDateChooser_fin.setDate(null);
        jtf_nombre.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_jrb_activo;
    private com.toedter.calendar.JDateChooser jDateChooser_fin;
    private com.toedter.calendar.JDateChooser jDateChooser_inicio;
    private javax.swing.JLabel jL_montoMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_modificar_campaña_sel;
    private javax.swing.JButton jbt_salir;
    private javax.swing.JLabel jl_activo;
    private javax.swing.JLabel jl_fin;
    private javax.swing.JLabel jl_montoMaximo;
    private javax.swing.JRadioButton jrb_activo_no;
    private javax.swing.JRadioButton jrb_activo_si;
    private javax.swing.JTable jt_campañas;
    private javax.swing.JTextField jtf_montoMaximo;
    private javax.swing.JTextField jtf_montoMinimo;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
