/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;
    
import aivon.entidades.Producto;
import aivon.entidades.Revendedor;
import aivon.modelos.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ezequiel
 */
public class ConsultaRankingRev extends javax.swing.JInternalFrame {
    private Conexion conexion;    
    private RevendedorData rd;
        private DefaultTableModel modelo;

    /**
     * Creates new form ConsultaRankingRev
     */
    public ConsultaRankingRev() {
        initComponents();
        try {
            conexion = new Conexion();
            rd = new RevendedorData(conexion);
            modelo = new DefaultTableModel();
            
            armaCabeceraTabla();
            cargaRevendedores();
            
        } catch (Exception e) {
        }
    }

    
//######################## ARMAR TABLA DE REVENDEDORES #########################    

    private void armaCabeceraTabla() {
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("ID");
        columnas.add("Revendedor");
        columnas.add("Nivel");
        columnas.add("Estrellas");
        columnas.add("Ganancias");
        
        columnas.forEach((it) -> {
            modelo.addColumn(it);
        });
        jt_revendedores.setModel(modelo);
    }
    
    private void borraFilasTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void cargaRevendedores() {
        this.borraFilasTabla();

        List<Revendedor> lista = rd.buscarRevendedores();
        lista.forEach((r) -> {
            String nombre = r.getNombre()+" "+r.getApellido();
            //modelo.addRow(new Object[]{r.getId_revendedor(), nombre, rd.calcularNivelRevendedorMejorado(r), rd.estrellasTotalesRevendedor(r), rd.gananciaFinalRevendedor(r)});
            modelo.addRow(new Object[]{r.getId_revendedor(), nombre, rd.calcularNivelRevendedorMejorado(r), rd.estrellasTotalesRevendedor(r), rd.gananciaFinalRevendedor(r)});
        });
        // Instanciamos el TableRowSorter y lo añadimos al JTable
            TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
            
            jt_revendedores.setRowSorter(elQueOrdena);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_revendedores = new javax.swing.JTable();
        jb_salir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("RANKING REVENDEDORES");

        jt_revendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_revendedores);

        jb_salir.setText("SALIR");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salir)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jb_salir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_salir;
    private javax.swing.JTable jt_revendedores;
    // End of variables declaration//GEN-END:variables
}
