/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.*;
import aivon.modelos.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ezequiel
 */
public class ConsultaPedidosPorCampaña extends javax.swing.JInternalFrame {
    
    private Conexion conexion;
    private CampañaData cd;
    private PedidoData ped;
    private RevendedorData rd;
    
    private DefaultTableModel modelo;
    
    private Campaña campaña;
    
    /**
     * Creates new form ConsultaPedidosPorCampaña
     */
    public ConsultaPedidosPorCampaña() {
        initComponents();
        try {
            conexion = new Conexion();
            cd = new CampañaData(conexion);
            ped = new PedidoData(conexion);
            rd = new RevendedorData(conexion);
            
            modelo= new DefaultTableModel();
            armaCabeceraTabla();
            cargarComboBoxCampañas();
            //jcb_campañas.setSelectedItem(null);
            
        } catch (Exception e) {
        }
        
    }

//######################### TABLA PEDIDOS ######################################

private void armaCabeceraTabla() {
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Revendedor");
        columnas.add("Ingreso");
        columnas.add("Entrega");
        columnas.add("Pago");
        columnas.add("Estrellas");
        columnas.add("Cajas");
        columnas.add("Costo lista");
        columnas.add("Costo público");
        
        columnas.forEach((it) -> {
            modelo.addColumn(it);
        });
        jt_pedidos.setModel(modelo);
        
    }
    
    private void borraFilasTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void cargaPedidos() {
        this.borraFilasTabla();
        List<Pedido> lista = ped.listaPedidosCampaña(campaña);
        lista.forEach((p) -> {
            String nombre = p.getRevendedor().getNombre()+" "+p.getRevendedor().getApellido();
            double costo_lista = ped.costoPedido(p);
            double costo_pub = ped.costoPublicoPedido(p);
            modelo.addRow(new Object[]{nombre,p.getFecha_ingreso(), p.getFecha_entrega(), p.getFecha_pago(), p.getEstrellas_pedido(), p.getCantidad_cajas(), costo_lista, costo_pub});
         
        });

    }    
    private void cargaPedidosPagos() {
        this.borraFilasTabla();
        List<Pedido> lista = ped.listaPedidosPagosCampaña(campaña);
        lista.forEach((p) -> {
            String nombre = p.getRevendedor().getNombre()+" "+p.getRevendedor().getApellido();
            double costo_lista = ped.costoPedido(p);
            double costo_pub = ped.costoPublicoPedido(p);
            modelo.addRow(new Object[]{nombre,p.getFecha_ingreso(), p.getFecha_entrega(), p.getFecha_pago(), p.getEstrellas_pedido(), p.getCantidad_cajas(), costo_lista, costo_pub});
         
        });

    }  
//##############################################################################
//------------------------------------------------------------------------------
//###################### CARGANDO COMBO BOX DE CAMPAÑAS ########################

private void cargarComboBoxCampañas() {
    jcb_campañas.removeAllItems();
    List<Campaña> lista = cd.buscarCampañas();
    lista.forEach((it) -> {
        jcb_campañas.addItem(it);
        });
}

//##############################################################################

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_campañas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_pedidos = new javax.swing.JTable();
        jb_salir = new javax.swing.JButton();
        jb_buscar_pedidos = new javax.swing.JButton();
        jb_buscar_pagos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_fecha_inicio = new javax.swing.JLabel();
        jl_fecha_fin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jl_monto_min = new javax.swing.JLabel();
        jl_monto_max = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CONSULTA DE PEDIDOS POR CAMPAÑA");

        jLabel2.setText("CAMPAÑA");

        jcb_campañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_campañasActionPerformed(evt);
            }
        });

        jt_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_pedidos);

        jb_salir.setText("SALIR");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jb_buscar_pedidos.setText("BUSCAR PEDIDOS");
        jb_buscar_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_pedidosActionPerformed(evt);
            }
        });

        jb_buscar_pagos.setText("BUSCAR PEDIDOS PAGOS");
        jb_buscar_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_pagosActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA INICIO");

        jLabel4.setText("FECHA FIN");

        jLabel6.setText("MONTO MAX");

        jLabel7.setText("MONTO MIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_salir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcb_campañas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addComponent(jb_buscar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_buscar_pagos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jl_fecha_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl_fecha_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jl_monto_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl_monto_max, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                .addGap(116, 116, 116)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_campañas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jl_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jl_fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jb_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jl_monto_min, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jl_monto_max, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jcb_campañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_campañasActionPerformed
        // TODO add your handling code here:
        campaña = (Campaña) jcb_campañas.getSelectedItem();
        if (campaña!=null) {
            jl_fecha_inicio.setText(campaña.getFecha_inicio().toString());
            jl_fecha_fin.setText(campaña.getFecha_fin().toString());
            jl_monto_min.setText(String.valueOf(campaña.getMonto_min()));
            jl_monto_max.setText(String.valueOf(campaña.getMonto_max()));
        }
        
        
    }//GEN-LAST:event_jcb_campañasActionPerformed

    private void jb_buscar_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_pedidosActionPerformed
        // TODO add your handling code here:
        campaña = (Campaña) jcb_campañas.getSelectedItem();
        if (campaña!=null) {
            this.cargaPedidos();
        }
    }//GEN-LAST:event_jb_buscar_pedidosActionPerformed

    private void jb_buscar_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_pagosActionPerformed
        // TODO add your handling code here:
        campaña = (Campaña) jcb_campañas.getSelectedItem();
        if (campaña!=null) {
            this.cargaPedidosPagos();
        }
    }//GEN-LAST:event_jb_buscar_pagosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar_pagos;
    private javax.swing.JButton jb_buscar_pedidos;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<Campaña> jcb_campañas;
    private javax.swing.JLabel jl_fecha_fin;
    private javax.swing.JLabel jl_fecha_inicio;
    private javax.swing.JLabel jl_monto_max;
    private javax.swing.JLabel jl_monto_min;
    private javax.swing.JTable jt_pedidos;
    // End of variables declaration//GEN-END:variables
}
