/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.Campaña;
import aivon.entidades.Pedido;
import aivon.entidades.Revendedor;
import aivon.modelos.CampañaData;
import aivon.modelos.Conexion;
import aivon.modelos.PedidoData;
import aivon.modelos.RevendedorData;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Genaro
 */
public class ConsultaCampañasPoRevendedor extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private Revendedor revendedor;
    private Campaña campaña;
    private PedidoData ped;
    private RevendedorData rd;
    private CampañaData cd;
    private DefaultTableModel modelo_campañas;

    /**
     * Creates new form ConsultaCampañasPoRevendedor
     */
    public ConsultaCampañasPoRevendedor() {
        initComponents();

        try {
            conexion = new Conexion();
            ped = new PedidoData(conexion);
            rd = new RevendedorData(conexion);
            cd = new CampañaData(conexion);
            modelo_campañas = new DefaultTableModel();
            armaCabeceraTablaCampañasXRevendedor();
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jb_buscar_revendedor = new javax.swing.JButton();
        jtf_dni = new javax.swing.JTextField();
        jtf_nombre_rev = new javax.swing.JTextField();
        jtf_apellido_rev = new javax.swing.JTextField();
        jtf_activo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_campañas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_estrellas = new javax.swing.JTextField();
        jtf_nivel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jb_limpiar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();

        jLabel14.setText("ACTIVO");

        jb_buscar_revendedor.setText("BUSCAR REVENDEDOR");
        jb_buscar_revendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_revendedorActionPerformed(evt);
            }
        });

        jtf_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dniActionPerformed(evt);
            }
        });
        jtf_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_dniKeyTyped(evt);
            }
        });

        jtf_nombre_rev.setEditable(false);

        jtf_apellido_rev.setEditable(false);

        jtf_activo.setEditable(false);

        jLabel11.setText("DNI");

        jLabel12.setText("NOMBRE");

        jLabel13.setText("APELLIDO");

        jt_campañas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_campañas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CONSULTA DE CAMPAÑAS POR REVENDEDOR");

        jLabel15.setText("ESTRELLAS");

        jtf_estrellas.setEditable(false);

        jtf_nivel.setEditable(false);
        jtf_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nivelActionPerformed(evt);
            }
        });

        jLabel16.setText("NIVEL");

        jb_limpiar.setText("LIMPIAR");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        jb_salir.setText("SALIR");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_estrellas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jtf_nivel)))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtf_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jb_buscar_revendedor))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtf_activo)
                                                .addComponent(jtf_apellido_rev)
                                                .addComponent(jtf_nombre_rev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jb_limpiar)
                                .addGap(257, 257, 257)
                                .addComponent(jb_salir))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar_revendedor)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre_rev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_apellido_rev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_activo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jtf_estrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 129, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_limpiar)
                            .addComponent(jb_salir))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscar_revendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_revendedorActionPerformed
        // TODO add your handling code here:

        if (!"".equals(jtf_dni.getText())) {
            revendedor = rd.buscarRevendedor(jtf_dni.getText());

            if (revendedor != null) {
                jtf_dni.setEditable(false);
                jtf_nombre_rev.setText(revendedor.getNombre());
                jtf_apellido_rev.setText(revendedor.getApellido());
                jtf_estrellas.setText(String.valueOf(rd.estrellasTotalesRevendedor(revendedor)));
                
//                int estrellas = 0;
//                List<Pedido> pedidos = ped.listaPedidosPagosxREVENDEDOR(revendedor);
//                for(Pedido p : pedidos){
//                    estrellas+=ped.cantEstrellasPedido(p);
//                  
//                }
//                jtf_estrellas.setText(String.valueOf(estrellas));
                jtf_nivel.setText(String.valueOf(rd.calcularNivelRevendedorMejorado(revendedor)));

                if (revendedor.isActivo()) {
                    jtf_activo.setText("Sí");
                } else {
                    jtf_activo.setText("No");
                }
                this.cargarCampañas();
            } else {
                jtf_dni.setText("");
                jtf_dni.requestFocus();
            }
        } else {
            jtf_dni.requestFocus();
        }


    }//GEN-LAST:event_jb_buscar_revendedorActionPerformed
    private void armaCabeceraTablaCampañasXRevendedor() {
        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Numero Campaña");
        columnas.add("Nombre Campaña");
        columnas.add("Fecha Inicio");
        columnas.add("Fecha Fin");
        columnas.add("Ganancia");
        columnas.add("Estrellas");

        columnas.forEach((it) -> {
            modelo_campañas.addColumn(it);
        });
        jt_campañas.setModel(modelo_campañas);
//        jt_prod_pedidos.getColumnModel().getColumn(0).setMaxWidth(0);
//        jt_prod_pedidos.getColumnModel().getColumn(0).setMinWidth(0);
//        jt_prod_pedidos.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
//        jt_prod_pedidos.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

    }

    private void borraFilasTablaCampañasXRevendedor() {
        int a = modelo_campañas.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo_campañas.removeRow(i);
        }
    }

    private void cargarCampañas() {
        borraFilasTablaCampañasXRevendedor();
        List<Campaña> campañas = cd.buscarCampañas();
        campañas.forEach((c) -> {
            Pedido pedido = ped.buscarPedidoPago(revendedor.getId_revendedor(), c.getId_campaña());
            if (pedido != null) {
                double ganancia = ped.costoPublicoPedido(pedido) - ped.costoPedido(pedido);
                int estrellas = ped.cantEstrellasPedido(pedido);
                modelo_campañas.addRow(new Object[]{c.getId_campaña(), c.getNombre(), c.getFecha_inicio(), c.getFecha_fin(), ganancia, estrellas});

            }

        });

    }

    private void jtf_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dniActionPerformed

    private void jtf_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_dniKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!(((caracter < '0') || (caracter > '9')) && (caracter != '\b'))) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_dniKeyTyped

    private void jtf_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nivelActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed
    private void limpiar() {
        
        jtf_dni.setText("");
        
        jtf_apellido_rev.setText("");
        jtf_nombre_rev.setText("");
        jtf_activo.setText("");
        jtf_estrellas.setText("");
        jtf_nivel.setText("");
        borraFilasTablaCampañasXRevendedor();
        jtf_dni.setEditable(true);
        
      
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar_revendedor;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JTable jt_campañas;
    private javax.swing.JTextField jtf_activo;
    private javax.swing.JTextField jtf_apellido_rev;
    private javax.swing.JTextField jtf_dni;
    private javax.swing.JTextField jtf_estrellas;
    private javax.swing.JTextField jtf_nivel;
    private javax.swing.JTextField jtf_nombre_rev;
    // End of variables declaration//GEN-END:variables

   

}
