/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.Producto;
import aivon.modelos.Conexion;
import aivon.modelos.ProductoData;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezequiel
 */
public class ProductoAlta extends javax.swing.JInternalFrame {
    private Conexion conexion;
    private ProductoData pd;
    /**
     * Creates new form ProductoAlta
     */
    public ProductoAlta() {
        initComponents();
        try {
            conexion = new Conexion();
            pd = new ProductoData(conexion);
            jtf_nombre.requestFocus();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_jrb_activo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jrb_activo_si = new javax.swing.JRadioButton();
        jrd_activo_no = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_uso = new javax.swing.JTextField();
        jtf_volumen = new javax.swing.JTextField();
        jtf_costo_lista = new javax.swing.JTextField();
        jtf_costo_publico = new javax.swing.JTextField();
        jtf_estrellas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ALTA DE PRODUCTO");

        jLabel2.setText("PRODUCTO");

        jLabel3.setText("USO");

        jLabel4.setText("VOLUMEN (cm3)");

        jLabel5.setText("COSTO LISTA");

        jLabel6.setText("COSTO PÚBLICO");

        jLabel7.setText("ESTRELLAS");

        bg_jrb_activo.add(jrb_activo_si);
        jrb_activo_si.setText("SÍ");

        bg_jrb_activo.add(jrd_activo_no);
        jrd_activo_no.setText("NO");

        jLabel8.setText("ACTIVO");

        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyTyped(evt);
            }
        });

        jtf_uso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_usoKeyTyped(evt);
            }
        });

        jtf_volumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_volumenKeyTyped(evt);
            }
        });

        jtf_costo_lista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_costo_listaKeyTyped(evt);
            }
        });

        jtf_costo_publico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_costo_publicoKeyTyped(evt);
            }
        });

        jtf_estrellas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_estrellasKeyTyped(evt);
            }
        });

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CARGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(94, 94, 94))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_uso, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtf_nombre)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(jtf_volumen, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_estrellas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jrb_activo_si)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jrd_activo_no))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_costo_publico, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(jtf_costo_lista))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_uso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_costo_lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_costo_publico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_estrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jrb_activo_si)
                    .addComponent(jrd_activo_no))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyTyped
        // TODO add your handling code here:
        if(!(jtf_nombre.getText().length()<30)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_nombreKeyTyped

    private void jtf_usoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_usoKeyTyped
        // TODO add your handling code here:
        if(!(jtf_uso.getText().length()<15)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_usoKeyTyped

    private void jtf_costo_listaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_costo_listaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')|| (caracter > '9')) && (caracter != '\b') &&(caracter != '.')) {
            evt.consume();
        }
        if(!(jtf_costo_lista.getText().length()<7)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_costo_listaKeyTyped

    private void jtf_costo_publicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_costo_publicoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')|| (caracter > '9')) && (caracter != '\b') &&(caracter != '.')) {
            evt.consume();
        }
        if(!(jtf_costo_publico.getText().length()<7)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_costo_publicoKeyTyped

    private void jtf_volumenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_volumenKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!(((caracter < '0') || (caracter > '9')) && (caracter != '\b'))) {
            
        } else {
            
            evt.consume();
        }
        if(!(jtf_volumen.getText().length()<4)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_volumenKeyTyped

    private void jtf_estrellasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_estrellasKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!(((caracter < '0') || (caracter > '9')) && (caracter != '\b'))) {
            
        } else {
            
            evt.consume();
        }
        if(!(jtf_estrellas.getText().length()<3)){
            evt.consume();
        }
    }//GEN-LAST:event_jtf_estrellasKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Producto producto = new Producto();

        //#################### VALIDANDO STRINGS ###############################
        if (jtf_nombre.getText().length() > 4) {
            producto.setNombre(jtf_nombre.getText());
            if (jtf_uso.getText().length() > 4) {
                producto.setUso(jtf_uso.getText());
                //#################### VALIDANDO ENTEROS ###############################
                try {
                    int vol = Integer.parseInt(jtf_volumen.getText());
                    if (vol > 0) {
                        producto.setTamaño(vol);

                        try {
                            int estrellas = Integer.parseInt(jtf_estrellas.getText());
                            if (estrellas > 0) {
                                producto.setEstrellas(estrellas);
                                //#################### VALIDANDO DOUBLES ###############################
                                try {
                                    double costo_lista = Double.parseDouble(jtf_costo_lista.getText());
                                    if (costo_lista > 0) {
                                        producto.setCosto(costo_lista);
                                        try {
                                            double costo_publico = Double.parseDouble(jtf_costo_publico.getText());
                                            if (costo_publico > 0) {
                                                producto.setCosto_publico(costo_publico);
                                                //#################### VALIDANDO BOOL Y CARGA ##########################
                                                int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cargar estos datos?", "Alta producto", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                                                if (respuesta == 0) {
                                                    if (jrb_activo_si.isSelected()) {
                                                        producto.setActivo(true); // ALTA DEL PRODUCTO
                                                        pd.altaProducto(producto);
                                                        this.limpiar();
                                                    } else if (jrd_activo_no.isSelected()) {
                                                        producto.setActivo(false);
                                                        pd.altaProducto(producto); // ALTA DEL PRODUCTO
                                                        this.limpiar();
                                                    } else {
                                                        JOptionPane.showMessageDialog(this, "Debe seleccionar un estado activo o inactivo");
                                                    }
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(this, "Debe ingresar un costo público válido");
                                                jtf_costo_publico.setText("");
                                                jtf_costo_publico.requestFocus();
                                            }
                                        } catch (NumberFormatException e) {
                                            JOptionPane.showMessageDialog(this, "Debe ingresar un costo público válido");
                                            jtf_costo_publico.setText("");
                                            jtf_costo_publico.requestFocus();
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Debe ingresar un costo de lista válido");
                                        jtf_costo_lista.setText("");
                                        jtf_costo_lista.requestFocus();
                                    }
                                } catch (NumberFormatException e) {
                                    JOptionPane.showMessageDialog(this, "Debe ingresar un costo de lista válido");
                                    jtf_costo_lista.setText("");
                                    jtf_costo_lista.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad de estrellas entera");
                                jtf_estrellas.setText("");
                                jtf_estrellas.requestFocus();
                            }

                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad de estrellas entera");
                            jtf_estrellas.setText("");
                            jtf_estrellas.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe ingresar un volumen entero");
                        jtf_volumen.setText("");
                        jtf_volumen.requestFocus();
                    }

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un volumen entero");
                    jtf_volumen.setText("");
                    jtf_volumen.requestFocus();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar una descripción de uso\nde al menos 5 caracteres");
                jtf_uso.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar una descripción del producto\nde al menos 5 caracteres");
            jtf_nombre.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_jrb_activo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jrb_activo_si;
    private javax.swing.JRadioButton jrd_activo_no;
    private javax.swing.JTextField jtf_costo_lista;
    private javax.swing.JTextField jtf_costo_publico;
    private javax.swing.JTextField jtf_estrellas;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_uso;
    private javax.swing.JTextField jtf_volumen;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jtf_nombre.setText("");
        jtf_uso.setText("");
        jtf_volumen.setText("");
        jtf_costo_lista.setText("");
        jtf_costo_publico.setText("");
        jtf_estrellas.setText("");
        jrb_activo_si.setSelected(true);
        
        jtf_nombre.requestFocus();
    }
}
