/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.Revendedor;
import aivon.modelos.Conexion;
import aivon.modelos.HistoricoData;
import aivon.modelos.RevendedorData;
import java.awt.event.KeyEvent;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author MArio
 */
public class RevendedorAlta extends javax.swing.JInternalFrame {
    private Conexion conexion;
    private RevendedorData revendedor_data;
    private HistoricoData historico_data;
    private Revendedor revendedor;
    /**
     * Creates new form RevendedorAlta
     */
    public RevendedorAlta() {
        initComponents();
        try {
             conexion=new Conexion();
             revendedor_data=new RevendedorData(conexion);
             historico_data=new HistoricoData(conexion);
             
            
        } catch (Exception e) {
        }

        
    }
    private void Limpiar(){
        jtf_nombre.setText("");
        jtf_apellido.setText("");
        jtf_dni.setText("");
        jcb_activo.setSelectedIndex(0);
        Timer timer = new Timer();
        TimerTask task=new TimerTask(){
        int tic=0;
        @Override
        public void run(){
         jtf_aviso.setText("");
         setOpaque(false);
        }
    };
    timer.schedule(task,30000,5000000);
        jtf_aviso.setText("");
    }
    
    private void delay(String mensaje, int a, int b ){
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                jtf_aviso.setText(mensaje);
            }
        };
        timer.schedule(task, a*1000 , b*20000);
    }
     private void limpiarJL(JLabel var, int a, int b ){
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                var.setText(" ");
            }
        };
        timer.schedule(task, a*1000 , b*20000);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellido = new javax.swing.JLabel();
        jl_DNI = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jl_activo = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_apellido = new javax.swing.JTextField();
        jtf_dni = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jb_limpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jb_guardar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jtf_aviso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_activo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Alta Revendedoras");

        jl_nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_nombre.setText("Nombre:");

        jl_apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_apellido.setText("Apellido: ");

        jl_DNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_DNI.setText("DNI:");

        jl_telefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_telefono.setText("Telefono:");

        jl_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_email.setText("Email:");

        jl_activo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_activo.setText("Activo:");

        jtf_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_email.setText("jTextField1");

        jtf_telefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_telefono.setText("jTextField1");

        jtf_apellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_apellido.setText("jTextField1");

        jtf_dni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_dni.setText("jTextField1");

        jtf_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_nombre.setText("jTextField1");
        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyTyped(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jb_limpiar.setText("Limpiar");
        jb_limpiar.setToolTipText("Limpia todo los campos");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jb_guardar.setText("Guardar");
        jb_guardar.setToolTipText("Deben estar llenos lo campos");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jtf_aviso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtf_aviso.setForeground(new java.awt.Color(153, 0, 0));
        jtf_aviso.setToolTipText("Da informacion de lo que esta suceciendo");

        jLabel2.setText("Estado:");

        jcb_activo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcb_activo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "SI", "NO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtf_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_email)
                            .addComponent(jl_activo)
                            .addComponent(jl_telefono)
                            .addComponent(jl_DNI)
                            .addComponent(jl_apellido)
                            .addComponent(jl_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_dni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jb_limpiar)))
                                        .addGap(36, 36, 36)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jb_salir)
                                        .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jcb_activo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jb_salir)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombre)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_apellido)
                            .addComponent(jtf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_DNI)
                            .addComponent(jtf_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_telefono)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_email)
                            .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_activo)
                            .addComponent(jcb_activo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jb_limpiar))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jtf_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        this.Limpiar();
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        int cont=0;
        if("".equals(jtf_nombre.getText())){
            cont++;
            jtf_aviso.setText("No Debe estar vacio el NOMBRE");
            jtf_nombre.requestFocus();
        }
        if("".equals(jtf_apellido.getText())){
            cont++;
            jtf_aviso.setText("No Debe estar vacio el APELLIDO");
            jtf_apellido.requestFocus();
        }
        if("".equals(jtf_dni.getText())){
            cont++;
            jtf_aviso.setText("No Debe estar vacio el DNI");
            jtf_dni.requestFocus();
        }
        if(cont==0&&(JOptionPane.YES_NO_OPTION==JOptionPane.showConfirmDialog(this, "Esta correctos todos los datos??", "Guaradar Revendedora", JOptionPane.YES_NO_OPTION))){

            revendedor= new Revendedor();
            revendedor.setNombre(jtf_nombre.getText());
            revendedor.setApellido(jtf_apellido.getText());
            revendedor.setDni(jtf_dni.getText());
            revendedor.setEmail(jtf_email.getText());
            revendedor.setTel(jtf_email.getText());

            if ( jcb_activo.getSelectedItem().toString().equalsIgnoreCase("si")){
                revendedor.setActivo(true);
            }
            else{
                revendedor.setActivo(false);
            }
            revendedor_data.guardarRevendedor(revendedor);
            System.out.println(revendedor.getId_revendedor());
            if(revendedor.getId_revendedor()==0){
                this.Limpiar();
                System.out.println("Ya existe el alumno");
                jtf_aviso.setText("Ya existe el alumno");
                this.delay(" ", 3, 5);
            }else{
                jtf_aviso.setText("Alumno guardado con Exito");
                this.delay(" ", 3, 5);
                this.Limpiar();
            }
        }
        else{
            jtf_aviso.setText("Llene todos los campos Nombre, Apellido, DNI!!! ");
            //this.delay("Llene todos los campos Nombre, Apellido, DNI y FechaN ");
            this.delay(" ", 3, 5);
            //JOptionPane.showMessageDialog(this, "Deben estar los ca");

        }

    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyTyped
       char c = evt.getKeyChar();
        if ((Character.isDigit(c) == false) && !(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)&&!(Character.isLetter(evt.getKeyChar()))&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)) {
            evt.consume();
            jtf_aviso.setText("Solo letras");
        } 
//        else {
            
//         }
 //////////////////////////////////////////////
       if(jtf_nombre.getText().trim().isEmpty()){
            jtf_aviso.setText("Complete");
        }
///////////////////////////////////////        
        if(Character.isSpaceChar(c)||jtf_nombre.getText().isEmpty()){
            jtf_aviso.setText("Complete");
        }
        this.limpiarJL(jtf_aviso, 3, 2);

     
    }//GEN-LAST:event_jtf_nombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<String> jcb_activo;
    private javax.swing.JLabel jl_DNI;
    private javax.swing.JLabel jl_activo;
    private javax.swing.JLabel jl_apellido;
    private javax.swing.JLabel jl_email;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_telefono;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JLabel jtf_aviso;
    private javax.swing.JTextField jtf_dni;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
