/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aivon.vistas;

import aivon.entidades.Revendedor;
import aivon.modelos.Conexion;
import aivon.modelos.HistoricoData;
import aivon.modelos.RevendedorData;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author MArio
 */
public class RevendedorBaja extends javax.swing.JInternalFrame {
    private Conexion conexion;
    private RevendedorData revendedor_data;
    private HistoricoData historico_data;
    private Revendedor revendedor;
    /**
     * Creates new form RevendedorBaja
     */
    public RevendedorBaja() {
        initComponents();
        try {
             conexion=new Conexion();
             revendedor_data=new RevendedorData(conexion);
             historico_data=new HistoricoData(conexion);
             jb_baja.setEnabled(false);
         
        } catch (Exception e) {
        }
    }
    private void delay(String mensaje, int a, int b ){
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                jtf_aviso.setText(mensaje);
            }
        };
        timer.schedule(task, a*1000 , b*20000);
    }
    private void Limpiar(){
        jtf_nombre.setText("");
        jtf_apellido.setText("");
        jtf_dni.setText("");
        jtf_email.setText("");
        jcb_activo.setSelectedIndex(0);
        jtf_dni_buscar.setText("");
        jtf_telefono.setText("");
        jb_baja.setEnabled(false);
       this.delay("", 5, 5);
    }
    private boolean isDNI(){
        boolean res=true;  
        if(jtf_dni_buscar.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un DNI para buscar");
            this.Limpiar();
            return false;
         }
        if(!jtf_dni_buscar.getText().isEmpty()&&(jtf_dni_buscar.getText().length()<8)){
                JOptionPane.showMessageDialog(this, "Debe ingresar un DNI valido para buscar");
                return false;
            }
        return res;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_dni_buscar = new javax.swing.JTextField();
        jb_buscar_revendedor = new javax.swing.JButton();
        jl_buscar = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_apellido = new javax.swing.JLabel();
        jl_DNI = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_email = new javax.swing.JLabel();
        jl_activo = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jtf_apellido = new javax.swing.JTextField();
        jtf_dni = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_aviso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_activo = new javax.swing.JComboBox<>();
        jb_baja = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jb_limpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(14, 0), new java.awt.Dimension(14, 0), new java.awt.Dimension(14, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jb_salir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_dni_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_dni_buscarActionPerformed(evt);
            }
        });
        jtf_dni_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_dni_buscarKeyTyped(evt);
            }
        });
        getContentPane().add(jtf_dni_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 135, 107, -1));

        jb_buscar_revendedor.setText("BUSCAR");
        jb_buscar_revendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_revendedorActionPerformed(evt);
            }
        });
        getContentPane().add(jb_buscar_revendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 135, 77, -1));

        jl_buscar.setText("Ingrese DNI");
        getContentPane().add(jl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 114, 107, 15));

        jl_nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_nombre.setText("Nombre:");
        getContentPane().add(jl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 135, -1, -1));

        jl_apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_apellido.setText("Apellido: ");
        getContentPane().add(jl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 172, -1, -1));

        jl_DNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_DNI.setText("DNI:");
        getContentPane().add(jl_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 209, -1, -1));

        jl_telefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_telefono.setText("Telefono:");
        getContentPane().add(jl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 251, -1, -1));

        jl_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_email.setText("Email:");
        getContentPane().add(jl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 292, -1, -1));

        jl_activo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_activo.setText("Activo:");
        getContentPane().add(jl_activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 329, -1, -1));

        jtf_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_email.setCaretColor(new java.awt.Color(255, 51, 51));
        jtf_email.setEnabled(false);
        getContentPane().add(jtf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 288, 230, -1));

        jtf_apellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_apellido.setCaretColor(new java.awt.Color(255, 51, 51));
        jtf_apellido.setEnabled(false);
        getContentPane().add(jtf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 168, 140, -1));

        jtf_dni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_dni.setCaretColor(new java.awt.Color(255, 51, 51));
        jtf_dni.setEnabled(false);
        getContentPane().add(jtf_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 205, 100, -1));

        jtf_telefono.setCaretColor(new java.awt.Color(255, 51, 51));
        jtf_telefono.setEnabled(false);
        getContentPane().add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, -1));

        jtf_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtf_nombre.setToolTipText("");
        jtf_nombre.setCaretColor(new java.awt.Color(255, 51, 51));
        jtf_nombre.setEnabled(false);
        jtf_nombre.setName(""); // NOI18N
        getContentPane().add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 131, 140, -1));

        jtf_aviso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtf_aviso.setForeground(new java.awt.Color(153, 0, 0));
        jtf_aviso.setToolTipText("Da informacion de lo que esta suceciendo");
        getContentPane().add(jtf_aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 391, 342, 20));

        jLabel2.setText("Estado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 371, -1, -1));

        jcb_activo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcb_activo.setForeground(new java.awt.Color(0, 0, 0));
        jcb_activo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "SI", "NO" }));
        jcb_activo.setEnabled(false);
        jcb_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_activoActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 324, 68, -1));

        jb_baja.setText("Baja");
        jb_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_bajaActionPerformed(evt);
            }
        });
        getContentPane().add(jb_baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 238, 167, 40));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 305, 45, 48));

        jb_limpiar.setText("Limpiar");
        jb_limpiar.setToolTipText("Limpia todo los campos");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 305, 45, 48));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Baja Revendedoras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 46, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 90, 100));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 340, 40));

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_dni_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_dni_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dni_buscarActionPerformed

    private void jtf_dni_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_dni_buscarKeyTyped
       //#####  Controla que sean solo numeros y sin espacios  ########################
       Character caracter=evt.getKeyChar();
       if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
            jtf_aviso.setText("Solo numeros");
            this.delay("", 9, 9);
        }
//######    Controla que sean 8 digitos   ######################################
        if(!(jtf_dni_buscar.getText().length()<8)){
            evt.consume();
            jtf_aviso.setText("Solo 8 digitos");
            this.delay("", 9, 9);
        }
    }//GEN-LAST:event_jtf_dni_buscarKeyTyped

    private void jb_buscar_revendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_revendedorActionPerformed
//        String dni=jtf_dni_buscar.getText();
//        int cont=0;
//        if(jtf_dni_buscar.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Debe ingresar un DNI para buscar");
//            this.Limpiar();
//            cont++;
//         }
//        if(!jtf_dni_buscar.getText().isEmpty()&&(jtf_dni_buscar.getText().length()<8)){
//                JOptionPane.showMessageDialog(this, "Debe ingresar un DNI valido para buscar");
//                cont++;
//            }
        if(this.isDNI()){
            try {
                revendedor=new Revendedor();
                revendedor=revendedor_data.buscarRevendedor(jtf_dni_buscar.getText());
                jtf_nombre.setText(revendedor.getNombre());
                jtf_apellido.setText(revendedor.getApellido());
                jtf_dni.setText(revendedor.getDni());
                jtf_email.setText(revendedor.getEmail());
                jtf_telefono.setText(revendedor.getTel());
                if(revendedor.isActivo()){
                    jcb_activo.setSelectedIndex(1);
                }
                else{
                    jcb_activo.setSelectedIndex(2);
                }
                jb_baja.setEnabled(true);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(this, "No existe Revendedor para ese DNI: "+jtf_dni_buscar.getText());
            }
            
            
        }
        //this.Limpiar();
    }//GEN-LAST:event_jb_buscar_revendedorActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
            this.Limpiar();
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_bajaActionPerformed
        if((JOptionPane.YES_NO_OPTION==JOptionPane.showConfirmDialog(this, "Seguro que desea inhabilitar el Revendedor", "Inhabilitar Revendedor", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE))){
            revendedor_data.inhabilitarRevendedor(jtf_dni_buscar.getText());
            this.Limpiar();
            this.delay("Revendedor inhabilitado con Exito", 6, 6);
        }
        else{
            
        }
                
        this.delay("", 4, 4);
    }//GEN-LAST:event_jb_bajaActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jcb_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_activoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jb_baja;
    private javax.swing.JButton jb_buscar_revendedor;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JComboBox<String> jcb_activo;
    private javax.swing.JLabel jl_DNI;
    private javax.swing.JLabel jl_activo;
    private javax.swing.JLabel jl_apellido;
    private javax.swing.JLabel jl_buscar;
    private javax.swing.JLabel jl_email;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_telefono;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JLabel jtf_aviso;
    private javax.swing.JTextField jtf_dni;
    private javax.swing.JTextField jtf_dni_buscar;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
